[project]
name = "password-manager-contract"
description = "A decentralized password manager smart contract"
authors = ["Your Name <your.email@example.com>"]
telemetry = false
cache_dir = "./.clarinet"

[contracts.password-manager]
path = "contracts/password-manager.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2